node_js:
- "10"
- "12"
- "14"
env:
- DEBUG_VERSION=2
- DEBUG_VERSION=3
- DEBUG_VERSION=4
sudo: false
language: node_js
script:
  - npm install --no-save debug@^$DEBUG_VERSION
  - npm run ci
after_success:
  - npm i -g codecov && codecov -t a62849b5-9006-4dd4-8334-94624d6d8ea2
